baseURL = 'http://example.org/'
languageCode = 'fr'
title = 'Juliane Casier'
[Params]
  author= 'Juliane Casier'
  description="Développeuse Web React Node Next"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [menu]
[[menu.home]]
  name = 'Juliane Casier'
  url = '/'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'CV'
  url = '/cv'
  pageRef = '/cv'
  weight = 10
[[menu.main]]
  name = 'Projets'
  url = '/pages/projets'
  pageRef = '/pages/projets'
  weight = 20
[[menu.main]]
  name = 'Contact'
  url = '/pages/contact'
  pageRef = '/pages/contact'
  weight = 30

[[menu.footer]]
  name = 'Mentions légales'
  url = '/pages/mentions-legales'
  pageRef = '/pages/mentions-legales'
  weight = 10
[[menu.footer]]
  name = 'Accessibilité : conforme'
  url = '/pages/accessibilite'
  pageRef = '/pages/accessibilite'
  weight = 20
  [[menu.footer]]
  name = 'Ecoconception'
  url = '/pages/ecoconception'
  pageRef = '/pages/ecoconception'
  weight = 30
[[menu.footer]]
  name = 'Contact'
  url = '/pages/contact'
  pageRef = '/pages/contact'
  weight = 40
  [[menu.footer]]
  name = 'Plan du site'
  url = '/pages/plan-du-site'
  pageRef = '/pages/plan-du-site'
  weight = 50